### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by shumink** [shubhtuls/volumetricPrimitives#4]
Hi Shubhtuls,

After much investigation in the dataset, I've found some interesting properties in each mat files. They are `tsdf` and `closest points`. But in the paper, these are only needed when calculating the loss. Can you provide more information about them?

Thanks

**Comment by shubhtuls** [comment]
Hi,
When computing the 'Consistency Loss', we need to compute C(O, p) (Eqn 7.). As the 'Implementation details' paragraph in Sec 4 describes briefly, we do so only approximately by storing for each voxel the closest point to O (the 'closest points' field). Then, given any query point p, instead of computing the actual closest point in O to p, we simply use the closest point to the voxel  to which p belongs.

**Comment by shumink** [comment]
Hi, shubhtuls

Thank you so much for your clarification.
